---

- hosts: aws
  remote_user: ec2-user
  become: true
  vars_files:
    - vars.yml
  vars:
    ansible_ssh_private_key_file: "{{ key }}"
  tasks:
    - name: Transfer the script
      copy: src=test.sh dest=/home/ec2-user mode=0777

    - name: Execute the script
      command: sh /home/ec2-user/test.sh
